"""Training script for the two-detector time-domain signal/glitch separator.

Trains UNET1D_LSTM_ATT on HDF5 data generated by the CIT/Snellius pipeline.
All configuration is via command-line arguments so the script can be submitted
directly to a SLURM scheduler without editing.

Example (local):
    python scripts/train_td.py \
        --hdf5 data/strain_data_scaled_standard.h5 \
        --scaler data/standard_scaler.pkl \
        --out checkpoints/UNET1D_LSTM_ATT

Example (Snellius SLURM):
    python scripts/train_td.py \
        --hdf5 $TMPDIR/strain_data_scaled_standard.h5 \
        --scaler $TMPDIR/standard_scaler.pkl \
        --out $HOME/checkpoints/UNET1D_LSTM_ATT \
        --epochs 300 --batch-size 64 --workers 16
"""

import argparse
import logging
import os
import subprocess
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim.lr_scheduler import ReduceLROnPlateau
from torch.utils.data import DataLoader

from deepextractor.data import HDF5Dataset
from deepextractor.data.preprocessing import ChannelStandardScaler
from deepextractor.models import UNET1D_LSTM_ATT
from deepextractor.training import eval_fn_td, train_fn_td

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)s  %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _best_gpu() -> int:
    """Return the GPU index with the most free memory."""
    try:
        result = subprocess.run(
            ["nvidia-smi", "--query-gpu=memory.free", "--format=csv,noheader,nounits"],
            stdout=subprocess.PIPE, text=True, check=True,
        )
        free = [int(x) for x in result.stdout.strip().split("\n")]
        return free.index(max(free))
    except Exception:
        return 0


def _load_scaler(path: str | None):
    """Load a ChannelStandardScaler (or sklearn scaler) from a pickle file."""
    if path is None:
        return None
    import pickle
    with open(path, "rb") as f:
        return pickle.load(f)


def _save_losses(out_dir: Path, prefix: str, start: int, end: int, losses: dict):
    for name, arr in losses.items():
        np.save(out_dir / f"{name}_{prefix}_{start}_to_{end}.npy", np.array(arr))


# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

def parse_args():
    p = argparse.ArgumentParser(description="Train UNET1D_LSTM_ATT separator")

    # --- Data ---
    p.add_argument("--hdf5", required=True,
                   help="Path to the scaled HDF5 training file")
    p.add_argument("--input-key",      default="noisy_glitch_train")
    p.add_argument("--bg-key",         default="background_train")
    p.add_argument("--sig-key",        default="signal_only_train")
    p.add_argument("--val-input-key",  default="noisy_glitch_val")
    p.add_argument("--val-bg-key",     default="background_val")
    p.add_argument("--val-sig-key",    default="signal_only_val")
    p.add_argument("--scaler",         default=None,
                   help="Path to pickled ChannelStandardScaler (or None to skip)")

    # --- Model ---
    p.add_argument("--features",       nargs="+", type=int, default=[64, 128, 256, 512])
    p.add_argument("--use-lstm",       action="store_true", default=True)
    p.add_argument("--no-lstm",        dest="use_lstm", action="store_false")
    p.add_argument("--lstm-layers",    type=int, default=1)
    p.add_argument("--lstm-bidir",     action="store_true", default=True)
    p.add_argument("--no-lstm-bidir",  dest="lstm_bidir", action="store_false")
    p.add_argument("--use-mhsa",       action="store_true", default=True)
    p.add_argument("--no-mhsa",        dest="use_mhsa", action="store_false")
    p.add_argument("--attn-heads",     type=int, default=4)
    p.add_argument("--use-se",         action="store_true", default=True)
    p.add_argument("--no-se",          dest="use_se", action="store_false")
    p.add_argument("--norm",           default="bn", choices=["bn", "gn"])

    # --- Residual channel options ---
    p.add_argument("--residual",       action="store_true", default=False,
                   help="Add a residual channel (6-output model)")
    p.add_argument("--residual-mode",  default="true",
                   choices=["true", "sum", "sum_detach"])
    p.add_argument("--residual-weight", type=float, default=1.0)

    # --- Training ---
    p.add_argument("--epochs",         type=int,   default=250)
    p.add_argument("--batch-size",     type=int,   default=64)
    p.add_argument("--lr",             type=float, default=1e-4)
    p.add_argument("--workers",        type=int,   default=8)
    p.add_argument("--amp",            action="store_true", default=False,
                   help="Enable mixed-precision (disabled by default — unstable with whitened targets)")
    p.add_argument("--patience",       type=int,   default=5,
                   help="Early stopping patience (epochs without val improvement)")
    p.add_argument("--lr-patience",    type=int,   default=2,
                   help="ReduceLROnPlateau patience")
    p.add_argument("--lr-factor",      type=float, default=0.1)

    # --- Checkpointing / output ---
    p.add_argument("--out",            required=True,
                   help="Output directory for checkpoints and loss arrays")
    p.add_argument("--resume",         default=None,
                   help="Path to a .pth.tar checkpoint to resume from")
    p.add_argument("--save-every",     type=int,   default=10,
                   help="Save loss arrays every N epochs (0 = only at end)")

    # --- Device ---
    p.add_argument("--device",         default=None,
                   help="Torch device string. Auto-selects best GPU if None.")

    return p.parse_args()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    args = parse_args()

    # --- Device ---
    if args.device is None:
        if torch.cuda.is_available():
            gpu = _best_gpu()
            device = torch.device(f"cuda:{gpu}")
        else:
            device = torch.device("cpu")
    else:
        device = torch.device(args.device)
    logger.info("Using device: %s", device)

    # --- Output dirs ---
    out_dir = Path(args.out)
    loss_dir = out_dir / "losses"
    out_dir.mkdir(parents=True, exist_ok=True)
    loss_dir.mkdir(parents=True, exist_ok=True)

    # --- Scaler ---
    scaler = _load_scaler(args.scaler)
    if scaler is None:
        logger.warning("No scaler supplied — inputs will not be normalised")

    # --- Datasets & loaders ---
    train_ds = HDF5Dataset(
        hdf5_path=args.hdf5,
        input_key=args.input_key,
        background_key=args.bg_key,
        signal_key=args.sig_key,
        input_scaler=scaler,
    )
    val_ds = HDF5Dataset(
        hdf5_path=args.hdf5,
        input_key=args.val_input_key,
        background_key=args.val_bg_key,
        signal_key=args.val_sig_key,
        input_scaler=scaler,
    )
    train_loader = DataLoader(
        train_ds, batch_size=args.batch_size, shuffle=False,
        num_workers=args.workers, pin_memory=True,
    )
    val_loader = DataLoader(
        val_ds, batch_size=args.batch_size, shuffle=False,
        num_workers=args.workers, pin_memory=True,
    )
    logger.info("Train samples: %d  Val samples: %d", len(train_ds), len(val_ds))

    # --- Model ---
    out_channels = 6 if args.residual else 4
    model = UNET1D_LSTM_ATT(
        in_channels=2,
        out_channels=out_channels,
        features=tuple(args.features),
        use_lstm_bottleneck=args.use_lstm,
        lstm_layers=args.lstm_layers,
        lstm_bidirectional=args.lstm_bidir,
        use_mhsa_bottleneck=args.use_mhsa,
        attn_heads=args.attn_heads,
        use_se_on_skips=args.use_se,
        norm=args.norm,
    ).to(device)
    logger.info("Model: UNET1D_LSTM_ATT  out_channels=%d", out_channels)

    # --- Optimiser / scheduler ---
    optimizer = optim.Adam(model.parameters(), lr=args.lr)
    scheduler = ReduceLROnPlateau(
        optimizer, mode="min", factor=args.lr_factor, patience=args.lr_patience
    )
    loss_fn = nn.MSELoss()
    grad_scaler = torch.amp.GradScaler("cuda", enabled=args.amp and device.type == "cuda")

    # --- Resume ---
    start_epoch = 0
    best_val_loss = float("inf")
    if args.resume:
        ckpt = torch.load(args.resume, map_location=device, weights_only=False)
        model.load_state_dict(ckpt["state_dict"])
        optimizer.load_state_dict(ckpt["optimizer"])
        scheduler.load_state_dict(ckpt["scheduler"])
        start_epoch = ckpt.get("epoch", 0) + 1
        best_val_loss = ckpt["scheduler"]["best"]
        logger.info("Resumed from %s (epoch %d, best_val=%.4e)", args.resume, start_epoch, best_val_loss)

    # --- Training loop ---
    history = {
        "train_total": [], "train_bg": [], "train_sig": [],
        "val_total":   [], "val_bg":   [], "val_sig":   [],
    }
    if args.residual:
        history["train_res"] = []
        history["val_res"]   = []

    es_counter = 0

    for epoch in range(start_epoch, start_epoch + args.epochs):
        logger.info("Epoch %d/%d", epoch + 1, start_epoch + args.epochs)

        # Train
        train_result = train_fn_td(
            train_loader, model, optimizer, loss_fn, grad_scaler, device,
            residual_channels=args.residual,
            residual_weight=args.residual_weight,
            residual_mode=args.residual_mode,
            use_amp=args.amp,
        )
        # Validate
        val_result = eval_fn_td(
            val_loader, model, device,
            residual_channels=args.residual,
            residual_weight=args.residual_weight,
        )

        if args.residual:
            train_total, train_bg, train_sig, train_res = train_result
            val_total,   val_bg,   val_sig,   val_res   = val_result
            history["train_res"].append(train_res)
            history["val_res"].append(val_res)
            logger.info(
                "LR=%.3e | train total=%.4e bg=%.4e sig=%.4e res=%.4e | "
                "val total=%.4e bg=%.4e sig=%.4e res=%.4e",
                optimizer.param_groups[0]["lr"],
                train_total, train_bg, train_sig, train_res,
                val_total,   val_bg,   val_sig,   val_res,
            )
        else:
            train_total, train_bg, train_sig = train_result
            val_total,   val_bg,   val_sig   = val_result
            logger.info(
                "LR=%.3e | train total=%.4e bg=%.4e sig=%.4e | "
                "val total=%.4e bg=%.4e sig=%.4e",
                optimizer.param_groups[0]["lr"],
                train_total, train_bg, train_sig,
                val_total,   val_bg,   val_sig,
            )

        history["train_total"].append(train_total)
        history["train_bg"].append(train_bg)
        history["train_sig"].append(train_sig)
        history["val_total"].append(val_total)
        history["val_bg"].append(val_bg)
        history["val_sig"].append(val_sig)

        scheduler.step(val_total)

        # Checkpoint on improvement
        if val_total < best_val_loss:
            best_val_loss = val_total
            es_counter = 0
            ckpt = {
                "state_dict": model.state_dict(),
                "optimizer":  optimizer.state_dict(),
                "scheduler":  scheduler.state_dict(),
                "epoch":      epoch,
                "mode":       "td",
            }
            ckpt_path = out_dir / "checkpoint_best.pth.tar"
            torch.save(ckpt, ckpt_path)
            logger.info("Val improved to %.4e — saved %s", best_val_loss, ckpt_path)
        else:
            es_counter += 1
            logger.info("No val improvement (%d/%d)", es_counter, args.patience)

        if es_counter >= args.patience:
            logger.info("Early stopping at epoch %d", epoch + 1)
            break

        # Periodic loss saves
        if args.save_every > 0 and epoch % args.save_every == 0:
            _save_losses(loss_dir, "periodic", start_epoch, epoch, history)

    # Final loss save
    _save_losses(loss_dir, "final", start_epoch, epoch, history)
    logger.info("Training complete. Losses saved to %s", loss_dir)


if __name__ == "__main__":
    main()
